### ISSUE TITLE
Waypoints / Highlights from Komoot no longer exported in the gpx file?

### ISSUE THREAD

**Issue by LucVanhoorickx** [fjungclaus/KomootHighlightsAsGpxExporter#1]
Hello,

First: thanks for this great extension!

It worked well for a couple of weeks, using the Chrome 'Save as GPX (+track)' button.  Now the gpx files are still exported, but they no longer contain any of the Komoot highlights as waypoints. The file only has trkpt's.  I can't attach the .gpx files here, but below some example excerpts, first from an export last month where it was still working, second from one today where there's no waypoints in the file (even though there are Komoot highlights - tested it with the same route/file as the one for which it worked previously).

Any ideas how this might be? Thanks so much, and hope this helps.

Kind regards,
Luc. 

Older export, has wpt's:

<?xml version='1.0' encoding='UTF-8'?>
<gpx version="1.1" creator="https://www.komoot.de" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>Tour=1883711447, Cycling Vlaanderen Ghent Gravel Escape lang via Hooggoed van Fashion for Cycling</name>
    <author>
      <link href="https://www.komoot.com/nl-nl/tour/1883711447">
        <text>Tampermonkey, https://dl4xj.de, KomootHighlightsAsGpxExporter, V0.9.11</text>
        <type>text/html</type>
      </link>
    </author>
 </metadata>
 <wpt lat="51.013333" lon="3.746316">
   <ele>49.7</ele>
   <name>Doorheen het Liedermeerspark</name>
   <desc>Bij oorsprong was het Liedermeerspark wellicht voor voetgangers bedoeld, maar fietsen is er niet verboden, en de verlorenbroodwegel doorheen het park en langs de vijver is best wel leuk fietsen. Mits de vanzelfsprekende hoffelijkheid, uiteraard.</desc>
   <sym>Flag, Blue</sym>
 </wpt>
 <wpt lat="51.021182" lon="3.707647">
   <ele>10.7</ele>
   <name>Fietsbrug over de ringvaart</name>
   <desc>Part of the Cyclinghighway F7 Gent Kortrijk
https://fietssnelwegen.be/f7</desc>
   <sym>Flag, Blue</sym>
 </wpt>

Recent file, no wpt's at all:

<?xml version='1.0' encoding='UTF-8'?>
<gpx version="1.1" creator="https://www.komoot.de" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>Tour=1926541391, FG Gravel Meets Wind and World History lang met Wijnendale</name>
    <author>
      <link href="https://www.komoot.com/nl-nl/tour/1926541391">
        <text>Tampermonkey, https://dl4xj.de, KomootHighlightsAsGpxExporter, V0.9.11</text>
        <type>text/html</type>
      </link>
    </author>
 </metadata>
 <trk>
  <name>FG Gravel Meets Wind and World History lang met Wijnendale</name>
  <trkseg>
   <trkpt lat="51.025522" lon="2.870832">
     <ele>6</ele>
     <time>2024-10-24T15:01:21.738Z</time>
   </trkpt>

**Comment by fjungclaus** [comment]
Hi Luc,
thank you for reporting this.
I just checked it ... and yes ... same problem here.
A quick debug session revealed that komoot did some changes to naming and layout of some data structures from which I fetch "my" data of highlights and POIs.
Unfortunately you're always in danger of such problems when scraping data out of a web page without using an official API ;)
But this should be fixable. I'll dig into this during the weekend.

Regards, Frank

**Comment by LucVanhoorickx** [comment]
Ow wow, thanks so much for checking and responding!  Indeed, strange that there’s no API or official way to do this, so all the more reason why your app is so fantastic - being able to see the highlights as waypoints while biking is so cool :)

Thanks so much again and hope you’re having a nice weekend!

Kind regards,
Luc.

**Comment by fjungclaus** [comment]
Hello Luc,
there is a new version 0.9.13 of the script, which should fix the latest problems.
Simply using "Trigger Update" via the Tampermonkey dashboard should fetch the new script.
Please give it a try.

Regards, Frank

**Comment by LucVanhoorickx** [comment]
Yay, it works again! You rock, thanks and greetings!
